USWDS - Color: Includes emergency colors in state tokens
uswds/uswds-site pull request #1145
Opened 2021-02-01 16:22 UTC by gscottqueen

## IUSWDS - Color: Includes emergency colors in state tokens

closes USWDS - Color: Document emergency colors on site. #1139

## Description

- includes an update to the state colors intro descriptions in response to the new value tokens

## Additional information

![Screen Shot 2021-02-01 at 11 17 54 AM](https://user-images.githubusercontent.com/4613286/106486302-7f0b4000-647f-11eb-8cff-102945d17443.png)

2021-02-01 17:51 UTC, gscottqueen commented
@mejiaj tagging you here for a  review -

2021-02-01 18:55 UTC, mejiaj approved these changes
I agree with the change to add them to state tokens makes more sense. Thanks!

2021-02-11 17:53 UTC, thisisdano requested changes

2021-02-11 17:53 UTC, thisisdano commented on _data/settings/color.yml
> +    description: Use grade 80.
Remove description

```suggestion
    description:
```

2021-02-11 17:53 UTC, thisisdano commented on _data/settings/color.yml
> +    description: Use grade 60v.
Remove description

```suggestion
    description:
```

2021-02-11 18:30 UTC, gscottqueen commented on _data/settings/color.yml
> +    description: Use grade 80.
removed those descriptions

2021-02-11 18:30 UTC, gscottqueen commented on _data/settings/color.yml
> +    description: Use grade 60v.
👍

2021-02-11 18:42 UTC, thisisdano commented
Looks good. Ignoring Snyk as irrelevant for this PR.

2021-02-11 18:43 UTC, merged