External links compliance for Fractal/Federalist
uswds/uswds-site pull request #1332
Opened 2021-11-22 00:29 UTC by brunerae

Ensuring links indicate they lead to blog site or Google Form

## Description

Include a high-level description of the issue your pull request fixes; include only one issue per pull request. Please also link to the GitHub issue it resolves.

## Additional information

Include any of the following (as necessary): 

* Relevant research and support documents
* Type of content review needed: stylistic or copy editing
* Screenshot images
* Notes
* etc.

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2021-11-23 17:21 UTC, mejiaj approved these changes

2021-11-23 19:32 UTC, mejiaj commented
@brunerae @thisisdano the links using `https://federalist.fr.cloud.gov/preview/18f/web-design-standards` are broken. Changing it to `https://federalist.18f.gov/` doesn't seem to work.

Found in the `preview_baseurl` in frontmatter in the post:
https://github.com/uswds/uswds-site/blob/eba435affbaadec23130c68f4f5c8218a22c0beb/_posts/2017-04-26-fractal-federalist.md?plain=1#L12

Also in:
- 2017-07-25-oes-case-study.md
- 2018-02-22-nsf-seed-fund.md

2021-11-23 19:34 UTC, mejiaj requested changes
Need to get the new URL for `preview_baseurl`.

2021-12-28 20:32 UTC, thisisdano approved these changes

2021-12-28 20:35 UTC, thisisdano commented
That link may just be link rot — i'm not sure it's recoverable

2021-12-28 20:39 UTC, merged