'Getting started for devs' guide: added markdown for new content
uswds/uswds-site pull request #1360
Opened 2021-12-01 21:10 UTC by amyleadem

Updated the markup from the structure created in upstream branch: dw-add-getting-started-for-devs

2021-12-01 22:02 UTC, mejiaj requested changes
LGTM, just some minor changes.

2021-12-02 15:47 UTC, amyleadem commented on css/settings/_uswds-theme-color.scss
> +$theme-color-accent-cool:           #5e9732;
Apologies, I had accidentally pulled into a playground branch. Should be resolved now.

2021-12-02 15:47 UTC, amyleadem commented on css/settings/_variables.scss
> +$external-href: '[href^="http"]:not([href*="designsystem.digital.gov"])';
Apologies, I had accidentally pulled into a playground branch. Should be resolved now.

2021-12-02 15:56 UTC, amyleadem commented on pages/documentation/getting-started-developers/overview.md
> +  - href: /documentation/getting-started/developers/phase-three-customize/
All fixed. Thank you.

2021-12-02 15:59 UTC, amyleadem commented on pages/documentation/getting-started-developers/phase-one.md
> +[Phase 2: Compile &gt;](/documentation/getting-started/developers/phase-two-compile/)
Updated all local links with site.baseurl

2021-12-02 15:59 UTC, amyleadem commented on pages/documentation/getting-started-developers/phase-three.md
> +The [USWDS Settings page](/documentation/settings/) describes each of the settings available in the settings files, as well as the values the settings accept. Most settings accept design tokens, visi
Updated all local links with site.baseurl

2021-12-02 16:01 UTC, amyleadem commented on pages/documentation/getting-started-developers/phase-one.md
> +<p class="margin-top-0 site-note">You do want to use the source code, but you don't want to modify it to use it. Instead, in Phase 2, we'll discuss how to compile, theme, and extend the USWDS source
Updated. Thank you.

2021-12-06 16:02 UTC, thisisdano commented
Closed in favor of https://github.com/uswds/uswds-site/pull/1362

2021-12-06 16:02 UTC, closed without merging