Post dev tutorial edits_intro pages
uswds/uswds-site pull request #1411
Opened 2022-01-24 21:09 UTC by mikki-stacey

## Description

Per our user research, I've moved the "Before getting started" content to the "How to use USWDS" page because it applies to each persona, not just developers.

I've also updated the "Getting started for developers" intro page to link out to the tutorial site.

2022-01-24 21:53 UTC, mahoneycm approved these changes

2022-01-27 15:49 UTC, mejiaj requested changes
@mikki-stacey can you check the previews for [Overview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/Post-dev-tutorial-edits/documentation/getting-started-for-developers/) and [How to Use](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/Post-dev-tutorial-edits/how-to-use-uswds/) and make sure it's what you intended? I had to resolve some code conflicts.

Also in Overview, there's this section:
>Sass (use the latest version; we use the latest sass package from npm)

This part points to the latest version of Node. We should specify or move it up to the Node list item. 

![image](https://user-images.githubusercontent.com/3385219/151393747-e4297c50-cd26-4c99-96eb-1b02639e3f12.png)

2022-01-27 16:31 UTC, mikki-stacey commented
@mejiaj , thank you for catching those link issues. I've proposed a few revisions to that list. Let me know if it looks good to you!

2022-01-27 16:45 UTC, mejiaj approved these changes

2022-01-27 17:46 UTC, merged