Copyedit round 1 icon
uswds/uswds-site pull request #1435
Opened 2022-02-10 18:30 UTC by mikki-stacey

## Description
Revised for grammar, consistency, and accessibility

2022-02-10 18:31 UTC, mikki-stacey commented
@mejiaj , in the implementation file, please confirm whether uswds-gulp is correct or if we should revise to uswds-compile.

2022-02-18 14:24 UTC, mejiaj requested changes
Noted reference to uswds-compile, instead of gulp.

2022-03-09 15:50 UTC, mejiaj approved these changes

2023-03-08 00:38 UTC, thisisdano approved these changes

2023-03-08 00:39 UTC, merged