Updated banner
uswds/uswds-site pull request #1887
Opened 2022-11-08 18:33 UTC by jonathanbobel

## Description

New banner text and link for IDP updates

2022-11-08 19:43 UTC, thisisdano requested changes

2022-11-08 19:43 UTC, thisisdano commented on _layouts/landing.html
> +    USWDS design patterns:
```suggestion
    Introducing inclusive design patterns:
```

2022-11-08 19:43 UTC, thisisdano commented on pages/home.md
> +        url: patterns
Let's move this to position 2, after components

2022-11-08 20:25 UTC, jonadecker commented
Looks good to me!

2022-11-10 07:43 UTC, thisisdano approved these changes

2022-11-10 07:54 UTC, thisisdano commented
Merging over Circle fails:
- `test_build`: Armypubs site is down

2022-11-10 07:55 UTC, merged