USWDS-Site: Update PR template
uswds/uswds-site pull request #1955
Opened 2022-12-19 23:10 UTC by amyleadem

## Summary

## Related issue
Closes #1950

## Problem statement

## Solution

## Testing and review

2023-01-04 16:54 UTC, mejiaj requested changes
Looks good! Could we run this through a markdown linter to make sure sections are consistent?

2023-01-06 18:52 UTC, amyleadem commented
@mejiaj I ran this through `markdownlint` and resolved the issues it found. If you see anything else, please let me know!

2023-01-13 15:12 UTC, mejiaj approved these changes

2023-03-01 05:03 UTC, thisisdano approved these changes

2023-03-01 05:03 UTC, merged