adding touchpoints top tasks survey to site banner
uswds/uswds-site pull request #2006
Opened 2023-02-14 16:53 UTC by bonnieAcameron

## Adding touchpoints survey to site banner

## Description

Jacline and I have updated the site banner by:

1. Removing the patterns library content
2. Adding the link to the top tasks survey with custom text 
3. changing the color of the banner

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2023-02-14 23:08 UTC, amyleadem requested changes
Looking good so far! I made a few suggestions and had a couple of questions for you.

2023-02-15 14:32 UTC, amyleadem commented on _layouts/landing.html
> +    class="bg-info-light padding-x-2 desktop:padding-x-4 padding-y-1 font-lang-4"
```suggestion
    class="bg-info-light padding-x-2 desktop:padding-x-4 padding-y-1 line-height-sans-5 font-lang-4"
```

2023-02-15 14:44 UTC, jaclinec commented on _layouts/landing.html
> +  >this 5 minute survey</a> so we can make the site work better for you!</a>
@amyleadem it should not be hyphenated. Thanks for catching that!

2023-02-15 15:24 UTC, bonnieAcameron commented on _layouts/landing.html
> -      onclick="ga('send', 'event', 'Viewed Together report', 'Clicked to view Together report from inside site');"
I don't think so. I think the previous team set up some tracking, but our GA on the backend isn't really configured to accept this information meaningfully.

2023-02-15 15:28 UTC, amyleadem commented
@jaclinec @bonnieAcameron I took the liberty of updating some of the classes on here, and I added a [preview link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/bc-jc-touchpoints-for-toptasks/) in the description. Let me know if it looks the way you wanted!

2023-02-15 15:49 UTC, bonnieAcameron reviewed
Love them, thank you!

2023-02-15 15:51 UTC, bonnieAcameron reviewed
looks good!

2023-02-15 16:03 UTC, amyleadem approved these changes
Looks good to me! Just want to get confirmation on the color choice (and other minor style changes) from @mejiaj before merging. 

Checked on Safari, Chrome, Firefox, Edge for Mac

2023-02-15 16:59 UTC, mejiaj approved these changes

2023-02-15 20:18 UTC, merged