USWDS-Site - In-page navigation: Create ability to opt-out
uswds/uswds-site pull request #2021
Opened 2023-03-07 23:17 UTC by amyleadem

# Summary
Created an opt-out setting that allows users to remove in-page navigation from a single page.

## Related issue

Closes #2010

## Preview links

- Component page
- Settings page

## Problem statement

## Solution

## Testing and review

2023-03-20 19:42 UTC, mejiaj approved these changes
Thanks for adding all of these changes!

2023-05-08 18:02 UTC, thisisdano requested changes
This is all good except I think we should move forward on @mejiaj's suggestion and convert the Collection headings to `h4`s

2023-05-12 15:16 UTC, amyleadem commented
@thisisdano Sending this back to fed final review because I have updated the [collection component page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-turn-off-inpage-nav/components/collection/) with @mejiaj 's suggestion. (Commit https://github.com/uswds/uswds-site/pull/2021/commits/17ccb974fe3f6dab3e3aa249b55c1fb31c92cbe8)

Please let me know if you need anything else.

2023-06-30 17:03 UTC, thisisdano approved these changes

2023-06-30 17:03 UTC, merged