USWDS-Site - Select: Add changelog for select uswds#5268
uswds/uswds-site pull request #2080
Opened 2023-05-02 20:37 UTC by mahoneycm

# Summary

**Add changelog to select component page.** Summarizes https://github.com/uswds/uswds/pull/5268

## Related issue

USWDS PR: https://github.com/uswds/uswds/pull/5268

Closes uswds/uswds#5047

## Preview link

Select component page

2023-05-09 13:30 UTC, mahoneycm commented
Closing in favor of #2096

2023-07-07 13:27 UTC, mejiaj requested changes
@mahoneycm can you fix conflicts and add reviewers when ready?

2023-07-14 18:32 UTC, amyleadem requested changes
@mahoneycm The changelog content looks good here. I'll approve once the build errors and merge conflicts resolve.

2023-07-20 16:43 UTC, mahoneycm commented
@amyleadem @mejiaj Updated and should be ready to merge! The build failure is from the nonexistent `3.6.0` release link

2023-07-20 16:44 UTC, mahoneycm commented
> **Warning**
> Changelog date must be updated

2023-07-20 22:13 UTC, amyleadem approved these changes
This looks good to me. 

Not particular to this particular PR, but I am wondering if we should start tagging `versionUswds` as N.N.N since it might not be as clear which release a change will belong to. No action needed at this time, just thinking out loud.

2023-07-28 17:08 UTC, thisisdano commented on _data/changelogs/component-select.yml
> +  versionUswds: 3.6.0
```suggestion
  versionUswds: N.N.N
```

2023-07-28 17:09 UTC, thisisdano approved these changes
Updated base to release branch and used a dummy version number

2023-07-28 17:10 UTC, merged