Create modal changelog item
uswds/uswds-site pull request #2117
Opened 2023-06-01 20:46 UTC by mahoneycm

# Summary

For https://github.com/uswds/uswds/pull/5315

## Preview link

Preview link:
[Modal changelog →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-modal-refactor-changelog/components/modal/#latest-updates)

2023-07-14 14:16 UTC, mejiaj commented on _data/changelogs/component-modal.yml
> +- date: NNNN-NN-NN
Noting that we'll need to add date before merge.

2023-07-14 14:16 UTC, mejiaj commented on _data/changelogs/component-modal.yml
> +  versionUswds: 3.5.0
Need to update version before merge.

2023-07-25 17:45 UTC, amyleadem requested changes
Generally looks good. I added a couple of small suggestions in the comments:

2023-07-25 21:09 UTC, mahoneycm commented on _data/changelogs/component-modal.yml
> +  summaryAdditional: This resolves issues when initialization is called more than once on a document.
To me, the main "change/improvement" revolves around the failsafe measures, and the JS multi-initialization prevention is a result of that. What do you think of this change? 

```yml
  summary: Updated JavaScript to include fallbacks and error messages when initialization cannot be completed.
  summaryAdditional: Additionally, this improved code consistency and prevented errors when trying to initialize modal twice.
```

Or would it be better practice to address the problem statement first like your example?

2023-07-28 18:39 UTC, amyleadem commented on _data/changelogs/component-modal.yml
> +  summaryAdditional: This resolves issues when initialization is called more than once on a document.
I like the wording on that update, @mahoneycm. Happy to defer to you about identifying the primary benefit here.

2023-07-28 18:42 UTC, amyleadem approved these changes

2023-11-06 17:51 UTC, merged