USWDS-Site - Header: Add variants table to guidance page
uswds/uswds-site pull request #2139
Opened 2023-06-13 15:31 UTC by mahoneycm

# Summary

**Added header variants table to guidance page.** This change also removes empty "**Using the header**" section.

## Related issue

Closes #1976 

## Preview link

Preview link:
Header variants →

## Problem statement

The Header guidance page was missing a variants table that can be found in other component guidance pages. There were also empty implementation sections due to each component containing variants in its frontmatter, which were not displayed in the sections.

## Solution

Move the `variants` out of the individual header variants front matter and include it in the base header guidance markdown page.

## Testing and review

1. Visit Header guidance page
2. View variants table and check for missing variants
3. Check each variant section and check for empty implementation sections _(screenshots below)_

### Screenshots

### Empty implementation section
![image](https://github.com/uswds/uswds-site/assets/25211650/62518b4b-2ecb-4b68-af35-20868462a65b)
[As seen on live site →](https://designsystem.digital.gov/components/header/#:~:text=of%20a%20megamenu.-,Using%20the%20basic%20header,-Package)

### New variants table
![image](https://github.com/uswds/uswds-site/assets/25211650/eadca766-57f9-4644-816b-1f6e82157052)

Before opening this PR, make sure you’ve done whichever of these applies to you:
- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `main`).
- [x] Run `npm test` and confirm that all tests pass.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.

2023-06-27 17:40 UTC, amyleadem commented on _data/changelogs/component-header.yml
> +    summary: Added Header variants table to guidance page.
```suggestion
    summary: Added variants table to guidance page.
```

2023-06-27 17:53 UTC, amyleadem requested changes
Thanks for finding and fixing this, @mahoneycm! Overall it looks good, I just added a couple suggestions for small tweaks in the changelog. 

- [x] Confirmed listed variants match those found in USWDS
- [x] Confirmed the empty implementation sections have been removed
- [x] Proofed for grammar and spelling

2023-06-27 17:53 UTC, amyleadem commented on _data/changelogs/component-header.yml
> +    summary: Added Header variants table to guidance page.
We should not capitalize the component name.

```suggestion
    summary: Added header variants table to guidance page.
```

2023-06-27 17:53 UTC, amyleadem commented on _data/changelogs/component-header.yml
> +    versionUswds: 3.6.0
No need to add a uswds version if the change is not tied to uswds code updates.
```suggestion
```

2023-07-03 20:05 UTC, mahoneycm commented
@mejiaj Bumping for review

2023-07-05 15:11 UTC, amyleadem approved these changes
Looks good to me!

Just flagging that we should update the changelog date before merge.

2023-07-14 15:57 UTC, mejiaj requested changes
Looks good. Confirming:

- [x] Variants table exists and is accurate.
- [x] Empty sections are gone.
- [x] Changelog entry exists.

@mahoneycm would you be able to briefly look into:

1. A visual regression with touchpoints. If confirmed, can you create an issue if there isn't one already?
2. Updating changelog date to today, so we can get this merged.

**Preview** (left) / **Live** (right)
![image](https://github.com/uswds/uswds-site/assets/3385219/25a0b139-6f38-41c2-984d-91dd49d0025b)

2023-07-14 16:20 UTC, mahoneycm commented
@mejiaj Date updated and issue created, chef! 🫡

https://github.com/uswds/uswds-site/issues/2186

2023-07-14 17:32 UTC, mejiaj approved these changes
Thanks! I've pulled in latest from `main` branch.

2023-07-17 15:09 UTC, merged