USWDS - Changelogs: Fix changelog dates
uswds/uswds-site pull request #2201
Opened 2023-07-19 20:35 UTC by mejiaj

# Summary

Replace placeholder dates with actual dates.

## Related issue

Closes #2199.

## Preview link

Preview link:

## Problem statement

_Summarize the problem this PR solves in a clear and concise statement._

## Solution

_Provide a summary of the solution this PR offers._

## Major changes

_For complex PRs, create a list of the significant updates made._

## Testing and review

_Share recommended methods for reviewing this change._

2023-07-19 21:09 UTC, amyleadem requested changes
Thanks for catching these! 
I added a couple of questions in the comments. Let me know if you have questions or comments.

2023-07-19 21:09 UTC, amyleadem commented on _data/changelogs/component-table.yml
> +  - date: 2023-06-17
Is this the accurate date for the merge? The PR shows it was merged [two days ago](https://github.com/uswds/uswds-site/pull/2143#event-9838545393).
```suggestion
  - date: 2023-07-17
```

2023-07-19 21:09 UTC, amyleadem commented on _data/changelogs/utilities.yml
> +  - date: 2023-05-26
Should these be the same release date as other 3.5.0 issues? [3.5.0](https://github.com/uswds/uswds/releases/tag/v3.5.0) was released on June 9. 
```suggestion
  - date: 2023-06-09
```

2023-07-20 13:18 UTC, mejiaj commented on _data/changelogs/component-identifier.yml
>      affectsContent: true
Which tag? Let's create a new issue for it. I'd like this PR scoped to fixing the dates.

2023-07-20 13:19 UTC, mejiaj commented
@amyleadem thanks for the suggestions. Re-requested review 😄

2023-07-20 14:20 UTC, amyleadem approved these changes
Thanks, @mejiaj!

2023-07-20 14:20 UTC, amyleadem commented on _data/changelogs/component-identifier.yml
>      affectsContent: true
Opened https://github.com/uswds/uswds-site/issues/2202 to address this

2023-07-20 16:50 UTC, merged