USWDS-Site: Add content tag to changelog table
uswds/uswds-site pull request #2203
Opened 2023-07-20 14:57 UTC by amyleadem

# Summary

Added the `Content` tag to the changelog table. 

## Related issue

Closes #2202

## Preview link
- Banner
- Identifier

## Problem statement

![image](https://github.com/uswds/uswds-site/assets/93996430/c3be78e7-8bee-4386-b4cb-0a3c2748db94)

## Solution

_Provide a summary of the solution this PR offers._

## Major changes

_For complex PRs, create a list of the significant updates made._

## Testing and review

_Share recommended methods for reviewing this change._

2023-07-20 16:48 UTC, mahoneycm approved these changes
Works great!

2023-07-20 16:52 UTC, mejiaj requested changes
Just want to make sure... What classifies as `Content` or what's separates it from `Guidance`?

Can we add that guidance to the changelog README?

2023-07-20 17:00 UTC, amyleadem commented
@mejia Good question. The content tag should be used for items that affect the content _inside the component itself_ (like the accessibility statement update shown in the screenshots above) vs an update that affects the component's related guidance for usage. It has already been [added to the README ](https://github.com/uswds/uswds-site/blob/main/_data/changelogs/_CHANGELOG-README.md?plain=1#L17). Does it need more clarification?

2023-07-28 19:58 UTC, mejiaj approved these changes

2023-07-28 21:10 UTC, thisisdano approved these changes

2023-07-28 21:11 UTC, merged