USWDS - Site: Add change log item for input border color
uswds/uswds-site pull request #2204
Opened 2023-07-20 15:36 UTC by mahoneycm

# Summary

Add change log item for https://github.com/uswds/uswds/pull/5397

## Preview link

Form change log →

2023-07-20 16:45 UTC, amyleadem requested changes
Added a couple of suggestions! Let me know if you have questions.

2023-07-20 16:45 UTC, amyleadem commented on _data/changelogs/component-form.yml
> +    summaryAdditional: Now the disabled border color only shows when the element is correctly disabled.
```suggestion
    summaryAdditional: Now the disabled border color only shows when the element is disabled.
```

2023-07-20 16:45 UTC, amyleadem commented on _data/changelogs/component-form.yml
> +    summary: Removed high-contrast disabled border from text input standard variants.
Last release, we changed all "high-contrast" references to "forced colors". Added a couple suggestions for structure and to suggest that the current disabled styles were not intentional: 
```suggestion
    summary: Fixed a bug that caused standard text input variants to show disabled styles when in forced colors mode.
```

2023-07-21 19:42 UTC, amyleadem requested changes
One more update after our team discussion yesterday. Can you update the version to 3.5.1 and update the base branch to `release-3.5.1`?

2023-07-21 19:42 UTC, amyleadem commented on _data/changelogs/component-form.yml
> +    versionUswds: 3.6.0
```suggestion
    versionUswds: 3.5.1
```

2023-07-24 13:38 UTC, mahoneycm commented
@amyleadem great catch! Committed your suggestion 👍

2023-07-28 21:13 UTC, thisisdano commented on _data/changelogs/component-form.yml
> +    versionUswds: 3.5.1
```suggestion
    versionUswds: N.N.N
```

While this is almost certainly going to be 3.5.1, I used dummy text here for consistency

2023-07-28 21:14 UTC, thisisdano approved these changes

2023-08-08 16:06 UTC, mejiaj approved these changes

2023-08-18 17:45 UTC, thisisdano approved these changes

2023-08-18 17:45 UTC, merged