USWDS-Site - Home: Update showcase
uswds/uswds-site pull request #2230
Opened 2023-08-08 18:34 UTC by bonnieAcameron

## Testing and review

1. Please review that I have uploaded the NIH.webp file in the appropriate location
2. Please ensure that the screenshot is of good quality 
3. Make sure that the grid still renders correctly

2023-08-10 16:14 UTC, amyleadem requested changes
@bonnieAcameron I added some notes related to the image size and location of the markup. Let me know if I can help at all with these edits. Other than that, looking good!

2023-08-10 16:14 UTC, amyleadem commented on pages/home.md
> +        <img src="{{ site.baseurl }}/img/webp/home/showcase/NIH.webp" alt="Preview image of National Institutes of Health Library" width="960" height="540">
To match the other images, the alt text should mention that it is an image of the website.
```suggestion
        <img src="{{ site.baseurl }}/img/webp/home/showcase/NIH.webp" alt="Preview image of National Institutes of Health Library home page" width="960" height="540">
```

2023-08-11 19:33 UTC, bonnieAcameron commented on img/webp/home/showcase/NIH.webp
removed and uploaded with one less than 50kb

2023-08-11 19:33 UTC, bonnieAcameron commented on pages/home.md
> -      </div>
Moved vote.gov to line 2

2023-08-11 19:34 UTC, bonnieAcameron commented
Hi @amyleadem ! I made all of the requested changes. Can you re-review for me? Thank you!

2023-08-21 18:20 UTC, amyleadem approved these changes
This looks good to me! Thanks, @bonnieAcameron. I'll pass it to @mahoneycm to get a second set of eyes on this and then we can pass to @thisisdano.

2023-08-22 13:44 UTC, mahoneycm approved these changes
Looks great! Thanks Bonnie

- [x] Checked multiple screensizes
- [x] Styles inline with other homepage previews
- [x] Expected screenreader output met

2023-10-16 14:39 UTC, mahoneycm commented
@mejiaj Could this be a quick merge when you have a sec?

2023-10-16 15:39 UTC, mejiaj approved these changes
Looks good;  we can merge once checks pass.

2023-10-16 20:34 UTC, mahoneycm commented
@mejiaj Bumping since checks passed 👍

2023-11-20 13:52 UTC, merged