Add Americana Stack to implementations
uswds/uswds-site pull request #2233
Opened 2023-08-08 19:04 UTC by lpsinger

Americana Stack is a Remix Stack for US Federal web sites on AWS. Includes US Web Design System, react-uswds, and pre-commit hooks for linting and type checking.

2023-11-20 14:02 UTC, mejiaj requested changes
Just a minor change on ID, otherwise LGTM.

2023-11-20 14:02 UTC, mejiaj commented on _data/implementations.yml
> +  id: vue-uswds
Duplicate ID to line 223.

2023-11-20 15:35 UTC, lpsinger commented on _data/implementations.yml
> +  id: vue-uswds
```suggestion
  id: remix-uswds
```

2023-11-20 17:17 UTC, mejiaj approved these changes
Thanks for the contribution!

2024-02-26 23:59 UTC, thisisdano approved these changes
Thank you!

2024-02-26 23:59 UTC, merged