USWDS-Site: Documentation updates for release 3.6.0
uswds/uswds-site pull request #2241
Opened 2023-08-11 20:57 UTC by mejiaj

# Summary

_Provide a one or two sentence summary of the update that can be used in the changelog._

## Related issue

Closes #_[issue_no]_

## Preview link

Preview link:

## Problem statement

_Summarize the problem this PR solves in a clear and concise statement._

## Solution

_Provide a summary of the solution this PR offers._

## Major changes

_For complex PRs, create a list of the significant updates made._

## Testing and review

_Share recommended methods for reviewing this change._

2023-08-15 17:03 UTC, mejiaj commented
Assigning team for visibility.

2023-08-23 20:03 UTC, amyleadem requested changes
@thisisdano I added a couple of optional suggestions to improve clarity in the changelogs. Other than those suggestions, this is looking good!

- [x] Confirmed that all 3.6.0 changelogs and doc updates are present
- [x] Confirmed grammar and spelling of documentation updates
- [x] Confirmed date on changelog entries
- [x] Confirmed version on changelog entries
- [x] Confirmed the visual presentation of content changes

2023-08-23 21:48 UTC, thisisdano approved these changes

2023-08-23 21:53 UTC, amyleadem approved these changes

2023-08-23 22:17 UTC, merged