USWDS-Site - Icon: Add note about icon color contrast
uswds/uswds-site pull request #2258
Opened 2023-08-25 17:57 UTC by amyleadem

# Summary

_Provide a one or two sentence summary of the update that can be used in the changelog._

## Related issue

Closes #2224

## Preview link

Preview link:

## Problem statement

_Summarize the problem this PR solves in a clear and concise statement._

## Solution

_Provide a summary of the solution this PR offers._

## Major changes

_For complex PRs, create a list of the significant updates made._

## Testing and review

_Share recommended methods for reviewing this change._

2023-09-06 21:09 UTC, amyleadem commented
@amycole501 Good point! I updated the link text to reflect the title of the article. Let me know if you want any changes!

2023-09-11 13:43 UTC, mahoneycm approved these changes
Lgtm! 👍

2023-09-25 17:35 UTC, mejiaj commented
@sarah-sch would you be able to review & approve? We can merge after.

2023-09-25 17:35 UTC, mejiaj approved these changes

2023-10-20 17:12 UTC, sarah-sch requested changes
Thanks for sharing, @amyleadem! Katie and I are suggesting some tweaks.

2023-10-20 17:12 UTC, sarah-sch commented on _components/icon/guidance/accessibility.md
**Check for sufficient color contrast.** Verify that the icon has a minimum contrast ratio of 3:1 against its background. See [WCAG 2.1 Techniques: Ensuring that a contrast ratio of 3:1 is provided 

@amyleadem - looked at this with @finekatie and we are suggesting some tweaks to maintain USWDS's conversational, approachable style: **Check for good color contrast.** Make sure that the icon has a minimum contrast ratio of 3:1 against its background.

2023-10-20 17:52 UTC, amyleadem commented on _components/icon/guidance/accessibility.md
@sarah-sch @finekatie 
Good improvement! I've updated the copy in [c634d58](https://github.com/uswds/uswds-site/pull/2258/commits/c634d58b6d8891247014c34784a25f1e6b3de988). Let me know if you want any changes.

2023-10-20 18:46 UTC, sarah-sch approved these changes
Looks good--thanks!

2023-10-20 20:40 UTC, merged