USWDS-Site - Migration guide: Add note about autoprefixer
uswds/uswds-site pull request #2319
Opened 2023-10-25 16:39 UTC by mahoneycm

# Summary

Added note about `Autoprefixer` requirement for CSS compilation to Migrating to 3.0 page. 

## Related issue

Closes #2296

## Preview link

Migrating to 3.0 page →

Changelog →

## Problem statement

Issue arose from a  [discussion](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1696437418207649?thread_ts=1696434410.341549&cid=C3F14AHSQ) in the public slack channel. Some users may be using the migration guide exclusively to set up their builds. Without this important piece of information, these users may run into issues with their CSS.

## Solution

Use note about Autoprefixer from Phase 2: Compile page in the Sass compiler instructions.

## Testing and review

1. Visit the Migrate to 3.0 page
2. Inspect new note re: Autoprefixer
3. Confirm no grammatical errors
4. Confirm placement is appropriate

2023-11-01 18:45 UTC, mahoneycm commented
@amyleadem Good thinking! Changed pushed up and conflicts resolved!

2023-11-08 20:20 UTC, amyleadem approved these changes
Looks good to me!
- [x] Confirmed that the site note on the compile page is unchanged
- [x] Confirmed that the migration guide now has a note about autoprefixer
- [x] Confirmed the note on the migration page is in a logical location
- [x] Confirmed the note on the migration page has content that makes sense in context
- [x] Confirmed the changelog is accurate and makes sense

2023-11-29 16:19 UTC, mejiaj requested changes
LGTM, changelog date and preview link for `phase-two` needs to be updated. Good to merge after.

2023-11-29 22:56 UTC, mahoneycm commented
@mejiaj I've updated the changelog date and `phase-two` link. Pa11y tests are failing in the pipeline but working passing!

2024-04-15 13:13 UTC, mahoneycm commented on _data/changelogs/docs-migration-v3.yml
> +  - date: 2023-11-29
> [!IMPORTANT]
> Neds updated changelog date on approval

2024-04-19 16:31 UTC, mahoneycm commented on _data/changelogs/docs-migration-v3.yml
> +  - date: 2023-11-29
Resolved in [a41ec1a](https://github.com/uswds/uswds-site/pull/2319/commits/a41ec1a53e6079f994cf24ef9a89dc5febc87253)

2024-04-19 16:33 UTC, mejiaj approved these changes

2024-04-29 20:47 UTC, mahoneycm commented
@thisisdano quick win PR ready for your review!

2024-06-07 19:15 UTC, thisisdano commented on _data/changelogs/docs-migration-v3.yml
> +  - date: 2024-04-29
```suggestion
  - date: 2024-06-07
```

2024-06-07 19:30 UTC, merged