USWDS-Site Pattern pages: Fix broken federalist links found in language selector section.
uswds/uswds-site pull request #2566
Opened 2024-03-27 20:01 UTC by mahoneycm

# Summary

Updates cloud pages links to match new pattern. This resolves broken links found on language selector previews.

## Related issue

Closes #2558

## Preview link

Two languages →

Three or more languages →

Selected multilingual content →

## Problem statement

There are broken links on the “Select a language” pattern pages. This was caused due to the cloud pages url pattern changing from `[app.cloud.gov](http://app.cloud.gov)` to `sites.pages.cloud.gov` .

## Solution

Update links to match new pattern.

## Testing and review

1. Visit each of the “Select a language” pattern pages.
2. Click the component preview photo.
3. Confirm it loads the storybook preview of the component.
4. Click the “Demo *component name*” button.
5. Confirm it loads the storybook preview of the component.
6. Confirm changelog is accurate and free of grammatical error.

> [!NOTE]
These pages are being ignored by html-proofer at this time. This is being explored further in #2169.
>

2024-03-27 23:04 UTC, amyleadem requested changes
Thanks for jumping on this so quickly @mahoneycm. I added a comment about using `federalist_base` for these links.

2024-03-28 17:20 UTC, finekatie approved these changes
LGTM

2024-03-28 17:56 UTC, mahoneycm commented on _includes/patterns/selected-content.html
> +  href="https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/iframe.html?id=components-language-selector--three-or-more-languages&amp;args=&amp;vi
Oh great catch! Looks like the only spot on the site that wasn't using that variable. Resolved in [fed601c](https://github.com/uswds/uswds-site/pull/2566/commits/fed601ca1f049c828c8b466e1b16b537cff4f363)

2024-04-01 18:26 UTC, sarah-sch approved these changes
Looks good!

2024-04-02 00:07 UTC, amyleadem approved these changes
This looks good! Thanks @mahoneycm.

> [!Note]
> I went ahead and pushed up a change to the changelogs that replaced `affectsContent` with `affectsGuidance` because the `content` tag is typically reserved for the content _inside_ a component or pattern. Let me know if you have any questions!

2024-04-11 15:45 UTC, mejiaj commented
@mahoneycm there are more HTMLProofer issues 

```bash
For the Links > External check, the following failures were found:

* At ./_site/patterns/complete-a-complex-form/establish-trust/index.html:2874:

  External link https://uxdesign.cc/build-trust-with-these-ux-guidelines-f3d547bb2014 failed (status code 520)

* At ./_site/patterns/complete-a-complex-form/progress-easily/index.html:2716:

  External link https://uxdesign.cc/trauma-informed-design-research-69b9ba5f8b08 failed (status code 520)
```

[Source →](https://app.circleci.com/pipelines/github/uswds/uswds-site/6485/workflows/a47355c8-6250-4241-aafa-527ffe6fa753/jobs/27479/parallel-runs/0/steps/0-104)

2024-04-11 20:19 UTC, merged