Add known issues for memorable date
uswds/uswds-site pull request #2716
Opened 2024-06-18 22:59 UTC by amyleadem

# Summary

Added a known issues section to the memorable date component page.

## Related issue
Closes #2682 

## Preview link

Memorable date page

## Testing and review

- Confirm a known issues section appears on the memorable date page
- Confirm the info alert is present at the top of the memorable date page
- On the known issues list item:
  - Confirm that the issue descriptions are accurate
  - Confirm that GitHub links work as expected
- Confirm there are no spelling or grammar issues
- Confirm the changelog is present and accurate on the memorable date page

2024-06-26 21:50 UTC, jaclinec requested changes
Everything looks great - I just have one correction to suggest before merging.

The second issue copy should be changed from "Users expected to be able to search the month input by either name or number but could do neither." to "Users expected to be able to search the month input by either name or number **but could only search by number.**"

2024-06-26 21:57 UTC, amyleadem commented
Thanks! I updated the summary in [704f417](https://github.com/uswds/uswds-site/pull/2716/commits/704f4172cf165c67eb0ac31ef5d3d6de5a81c5a5). Let me know if you need any other changes.

2024-06-26 22:11 UTC, jaclinec approved these changes
Perfect - approved! Thanks!

2024-06-26 22:16 UTC, amyleadem commented
@finekatie and @mahoneycm This is ready for your review!

2024-06-26 22:27 UTC, finekatie reviewed
I'm not seeing a new row for the change log - does that show up after you publish?

Wondering about the phrase "users experienced friction" in the third issue. I would suggest something plainer, but I see the same language is in the GH issue, so I'll leave it be. 

Other than these two things, LGTM :)

2024-06-27 13:38 UTC, mahoneycm approved these changes
LGTM!

2024-06-27 16:33 UTC, amyleadem commented
@finekatie It looked like we had a build failure on the page preview. The changelog should be visible now. Let me know if you need any changes!

2024-06-27 17:10 UTC, finekatie commented
> @finekatie It looked like we had a build failure on the page preview. The changelog should be visible now. Let me know if you need any changes!

Sorry - I think I re-requested review by accident? I approve and LGTM :)

2024-06-27 18:22 UTC, finekatie approved these changes
LGTM!

2024-11-06 22:37 UTC, thisisdano commented on _data/issues/memorable-date.yml
> +- date: 2024-04-29
These issues are closed

2024-11-06 22:39 UTC, thisisdano commented on _data/issues/memorable-date.yml
> +  summary: Screen reader users experienced friction with understanding what formatting was needed for the component.
```suggestion
  summary: Screen reader users experienced friction with understanding formatting requirements for each input.
```

2024-11-06 22:40 UTC, thisisdano approved these changes

2024-11-06 22:54 UTC, merged