USWDS-Site - Accessibility Failures: Fixed Accessibility Failures
uswds/uswds-site pull request #2783
Opened 2024-08-16 15:16 UTC by RachelCorsino

# Summary

Updated accessibility failures as found in the accessibility scan done on the USWDS site. These updates resolve accessibility violations.

## Related issue

Closes #2688 

## Preview link

Preview link:

## Problem statement

The website should provide an inclusive and accessible experience for all users, including those with disabilities, in compliance with Section 508 and WCAG guidelines. However, the current website contains accessibility failures that prevent users with disabilities from fully accessing and utilizing the website's features.

## Solution

Fixes have been made to the USWDS site based on the accessibility scan. Now users with disabilities can fully access and utilize the website's features.

## Testing and review

1. For color contrast failures, ensure updated color meets WCAG requirements.
2. *See comments for remaining failures

Before opening this PR, make sure you’ve done whichever of these applies to you:
- [X] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [X] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `main`).
- [X] Run `npm run prettier:scss` to format any Sass updates.
- [X] Run `npm test` and confirm that all tests pass.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.

2024-08-16 16:02 UTC, RachelCorsino commented
Most of the accessibility failures still need fixes but wanted to get some opinions on next steps for them.

**1. Deprecated ARIA roles must not be used**
1. There are 6 instances where `doc-endnotes` is being used which is now deprecated. It's recommended to update this to use `listitem` as the role value. 
**How can we update this markup?**

**2. Elements must only use supported ARIA attributes**
1. There are 2 instances where `aria-multiselectable` is being used which is now deprecated. It's recommended to remove this entirely, or add a `<details>` tag which would be able to take in the `aria-multiselectable` value.
**However, this code is component code, so should we create a new ticket for this to be updated within the necessary component?**

**3. Elements must meet minimum color contrast ratio thresholds**
1. The text being flagged for these failures are technically meeting WCAG requirements as they are considered a bold font and are at least 18.5px. 
**Do we still want to update this and make this text larger?**
2. A couple of these were updated, however the remaining colors that are failing are custom sass variables that are not meeting color contrast minimums. **Should we update to use USWDS color tokens or should we darken these variables?**
```
$pink-20v: #f8a897;
$pink-50v: #bc5843;

$gray-20-next: #eaece9;
```

**3. All touch targets must be 24px large, or leave sufficient space**
1. For these failures, they are occurring on any of the `family` (in this example) instances that are also serving as links
![Screenshot 2024-08-16 at 10 39 30 AM](https://github.com/user-attachments/assets/dd22ede6-7fff-445d-a351-9fe706841bde)
**Do we want to add an underline text-decoration to these since they are links? Or do we want to increase the margin around them to add sufficient space?**
2. Other failures occurring under this topic have to do with insufficient space on links within the component preview.
![Screenshot 2024-08-16 at 10 46 08 AM](https://github.com/user-attachments/assets/740b79d1-ae5c-44aa-9e57-28ec767e9f73)
**Would we want to create a separate ticket for these to have the component code updated?** 
3. For the date picker button (calendar icon), there is not sufficient space between neighbors.
![Screenshot 2024-08-16 at 10 57 00 AM](https://github.com/user-attachments/assets/20d97cf3-c655-4b32-8f0c-c73e9e1ffed8)
**Do we want to increase the size of the icon or account for a larger margin?**
**This is also component code. Do we want a separate ticket for this?**

**5. Documents must have <title> element to aid in navigation.**
**How can we add to the markup to add a `<title>` element?**

2024-08-16 16:44 UTC, mejiaj reviewed
Thanks for looking into these issues @RachelCorsino!

1. **Deprecated ARIA roles must not be used**. We're using [kramdown](https://github.com/kramdown/parser-gfm/tags). We should look into:
    1. Checking if there any updates or alternatives to this dependency.
    1. Checking if there any updates or alternatives to this dependency.
    1. If there aren't any viable updates/alternatives we should separate this issue to resolve elsewhere.
1. **Elements must only use supported ARIA attributes**. Where are these attributes being used? If LOE isn't small, we should separate into its own issue.
1. **Elements must meet minimum color contrast ratio thresholds** 
    1. Which text? If the LOE is small we should try to fix.
    2. Darkening colors seems like a lower LOE.
1. **All touch targets must be 24px large, or leave sufficient space**. 
    1. Separate issue with potential solutions for `family`.
    1. Component preview touch target issue might need to be separated if higher than small LOE.
1. Create issue in USWDS for date picker touch target (if there isn't one already).
1. Each MD page takes a `title` in Frontmatter. We should create a bug report if it's not working.

2024-08-16 16:44 UTC, mejiaj commented on css/uswds-next.scss
**issue**: Confirmed two issues less, but axe extension still shows two color contrast issues at `/next/`.

Before (left) | After (right)
![image](https://github.com/user-attachments/assets/173c48bb-7614-4379-a815-6088b1897ae7)

2024-08-16 17:46 UTC, RachelCorsino commented
> Thanks for looking into these issues @RachelCorsino!
> 
> 1. **Deprecated ARIA roles must not be used**. We're using [kramdown](https://github.com/kramdown/parser-gfm/tags). We should look into:
>    
>    1. Checking if there any updates or alternatives to this dependency.
>    2. Checking if there any updates or alternatives to this dependency.
>    3. If there aren't any viable updates/alternatives we should separate this issue to resolve elsewhere.
> 2. **Elements must only use supported ARIA attributes**. Where are these attributes being used? If LOE isn't small, we should separate into its own issue.
> 3. **Elements must meet minimum color contrast ratio thresholds**
>    
>    1. Which text? If the LOE is small we should try to fix.
>    2. Darkening colors seems like a lower LOE.
> 4. **All touch targets must be 24px large, or leave sufficient space**.
>    
>    1. Separate issue with potential solutions for `family`.
>    2. Component preview touch target issue might need to be separated if higher than small LOE.
> 5. Create issue in USWDS for date picker touch target (if there isn't one already).
> 6. Each MD page takes a `title` in Frontmatter. We should create a bug report if it's not working.


2. **Elements must only use supported ARIA attributes** - it looks like these failures are actually happening within the fieldset component. So this may be a component update rather than site update? It's happening for on the [Patterns: Create a user profile - Race and ethnicity](https://designsystem.digital.gov/patterns/create-a-user-profile/race-and-ethnicity/) page and the [Patterns: Select a language - Preferred language](https://designsystem.digital.gov/patterns/select-a-language/language-preferences/) page

3. **Elements must meet minimum color contrast ration thresholds** - this is being flagged on the `.site-title` class. Each page that it's being flagged on is using a different color behind the USWDS title, so if we want to take the darkening the color route, we'd be changing multiple colors. I can make that adjustment if that sounds like a good solution! This is what they currently look like:
![Screenshot 2024-08-16 at 12 29 37 PM](https://github.com/user-attachments/assets/a4b31304-4938-4179-a17a-6bdc6f6504e8)
![Screenshot 2024-08-16 at 12 30 06 PM](https://github.com/user-attachments/assets/2111689e-7276-4f5f-ad75-d0bf9c84bbdb)
![Screenshot 2024-08-16 at 12 30 16 PM](https://github.com/user-attachments/assets/c1f99c8b-f0f9-48bc-a29d-0a3f05baffbb)

4. **All touch targets must be 24px large, or leave sufficient space** - I think I need a little bit of clarification on the plan for this one.
Should I create an issue in the USWDS repo for the component preview failures (should this be one issue for each separate component or one ticket containing both components - I believe this is only happening in two components)
For the `family` related error, this is happening with more than just the `family` links, but it looks like they all have the `token` class which may be the only update we need to make for this. Should I go ahead and create an issue for updating the `token` class?

And just the confirm, the remaining tasks would be to look into kramdown, create issue for date picker touch target, and create bug report for `title` issue.

2024-08-16 20:36 UTC, mahoneycm commented
## aria-multiselectable

It looks like we're only adding `aria-multiselectable` to checkbox fieldsets. Since checkboxes support multi-selection by default, we should be able to remove them from the pattern previews.

MDN Docs mentions using checkboxes in place of multiselectable in [this example](https://arc.net/l/quote/mvujlhac)

2024-08-19 17:03 UTC, mejiaj commented on css/uswds-next.scss
@RachelCorsino if it's not too much effort, lets try to find a USWDS color token.

2024-08-19 17:16 UTC, mejiaj commented
@RachelCorsino re: questions

2. It's a component issue **if** there aren't any Site styles affecting this page. For example, custom site styles in preview.
3. Agreed, let's update those colors.
4. Again, let's create a USWDS issue or find one for this touch target error.
    1. Yes, we'd be updating the clickable `token` class to improve touch target size in a separate issue.

>And just the confirm, the remaining tasks would be to look into kramdown, create issue for date picker touch target, and create bug report for title issue.

Yes, let's briefly look into Kramdown or propose ideas for workarounds if there aren't [updates](https://github.com/gettalong/kramdown/tags) available.

2024-08-28 03:07 UTC, RachelCorsino commented
Adding these comments here based on the changes I made:

### Deprecated ARIA roles must not be used
- Didn't see any updates for Kramdown
- Updates have been made to md files to remove the `{:footnotes }` code that was adding the deprecated ARIA roles to elements. It has been changed to just using an ordered list which is working the same way in terms of styling as the previous code was, just without the added deprecated roles.

### Elements must meet minimum color contrast ratio thresholds
- Background colors against the U.S. Web Design System (USWDS) site title have been updated to meet color contrast minimums using USWDS color tokens rather than sass variables.
- Text on `/next` page has been updated to meet color contrast minimums using USWDS color tokens.

### All touch targets must be 24px large, or leave sufficient space
#### Touch Token Family
- The following issue has been created to look into this issue further:
[USWDS-Site - Bug: Token Class Touch Target Accessibility Failure #2796](https://github.com/uswds/uswds-site/issues/2796)

### Elements must only use supported ARIA attributes
- Removed `aria-multiselectable` from pattern previews

### Documents must have <title> element to aid in navigation
- I believe this is a false failure on the accessibility scan results. After searching the html using dev tools on the pages flagging this failure, it has been confirmed that they do in fact have a `<title>` element on the page.

Let me know if we should take a different route with any of these changes!

2024-08-28 03:20 UTC, RachelCorsino commented
@amycole501 @alex-hull - Can you help to confirm that the following accessibility failures are false positives?

### All touch targets must be 24px large, or leave sufficient space
#### Date Picker Button
- On the `./components/date-picker` page, it is flagging the date picker calendar icon button as having "insufficient space between targets". After reviewing this, our calendar button touch target is larger than minimum requirement of 24px by 24px.
- On the `./footer` page, the following elements are being flagged for having insufficient space between neighbors as well:
```
<a href="tel:1-800-555-5555">&lt;(800) 555-GOVT&gt;</a>
<a href="mailto:info@agency.gov">&lt;info@agency.gov&gt;</a>
```
I also believe this to be a false positive as it does look like we have sufficient space to meet wcag minimums for these elements, but can you confirm.

Thank you!

2024-08-28 13:56 UTC, amycole501 commented
I can confirm that the calendar button exceeds the minimum 24x24 requirement. I also checked both the date picker and footer pages in Axe, Wave, and Siteimprove (which flagged issues for not meeting enhanced, AAA sizes) and the button and links didn't get flagged for any AA issues.

 I'm curious if the testing requirement is instead set to the enhanced target size? We aren't required to meet AAA as part of Section 508 however we have it on our radar to incrementally reach that goal in the future. https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html

2024-08-28 14:00 UTC, alex-hull commented
Can also confirm that these meet the requirements for minimum. There appears to be two false positives in Siteimprove as well. Within that, it is referring to the minimum criteria. I do not think we can change what the automated tests are testing for (unless I'm unaware of this...could be very true).

2024-08-28 14:40 UTC, annepetersen commented
I thought SiteImprove had options for this, but I could be wrong. Worth poking around in their documentation for, I think

2024-08-28 14:46 UTC, amycole501 commented
You can ignore false positives in Siteimprove, you can do it one issue at a time per page. @RachelCorsino which software is flagging the issue you're asking us to investigate?

2024-08-28 16:32 UTC, RachelCorsino commented
@amycole501 - The accessibility scan was done via [cloud pages beta accessibility scans](https://pages.cloud.gov/sites/379/builds/378612/scans) where it showed failures for those couple instances.

Thank you, Amy and @alex-hull for confirming the false failures!

2024-08-29 13:41 UTC, mahoneycm commented
> @amycole501 - The accessibility scan was done via [cloud pages beta accessibility scans](https://pages.cloud.gov/sites/379/builds/378612/scans) where it showed failures for those couple instances.
> 
> Thank you, Amy and @alex-hull for confirming the false failures!

For reference, it looks like the accessibility scan might use Axe. The documentation link points to Deque.com/Axe.

I'm unable to reproduce certain failures using the Axe browser plugin.

![image](https://github.com/user-attachments/assets/12f58e85-51bb-44fd-aae4-99346227784b)

2024-08-30 19:41 UTC, mahoneycm reviewed
Found a couple things we might want to address / discuss before moving forward.

**polish:** Can you add preview links to the affected pages? It was difficult to find some of the pages to test.

**polish:** Can you provide a formatted list of the failures we should be checking? There are notes in the comments but it can be confusing to find what's outdated and what is relevant.

2024-08-30 19:41 UTC, mahoneycm commented on _next/03-03-team.md
> +navbar_color: "mint-50"
Confirming color meets color contrast minimums

| Before | After |
|--------|--------|
| <img width="377" alt="image" src="https://github.com/user-attachments/assets/78da825a-90f6-42ef-b4dc-175059277794"> | <img width="377" alt="image" src="https://github.com/user-attachments/assets/3845d96a-e32d-4dd7-9598-eea99bc515dc"> |

2024-08-30 19:41 UTC, mahoneycm commented on _next/03-04-community.md
> +navbar_color: "gold-50v"
Confirming color meets color contrast minimums

| Before | After |
|--------|--------|
| <img width="523" alt="image" src="https://github.com/user-attachments/assets/6aa83310-d184-430a-bac3-7524c5d54f63"> |<img width="523" alt="image" src="https://github.com/user-attachments/assets/fd69e39c-dba2-4851-a649-b1b6c20ccc54">

2024-08-30 19:41 UTC, mahoneycm commented on _next/03-05-improve.md
> +navbar_color: "red-cool-50"
Confirming color meets color contrast minimums

| Before | After |
|--------|--------|
| <img width="552" alt="image" src="https://github.com/user-attachments/assets/754cf094-40ad-4006-8d66-a89f1b0031c9"> | <img width="552" alt="image" src="https://github.com/user-attachments/assets/b28fa0ed-ffb0-465c-9dfa-7e251d1e7466"> |

2024-08-30 19:41 UTC, mahoneycm commented on _next/04-00-looking-ahead.md
## Citation regression

The citation section looks good but I noticed the following regression.

**issue (potentially blocking):** The refactored citations no longer provide links to/from references.

Note the missing `↲` icon

| Before | After |
|--------|--------|
| <img width="319" alt="image" src="https://github.com/user-attachments/assets/b86e4c13-36b6-4aef-8af7-b205d8cb967e"> | <img width="330" alt="image" src="https://github.com/user-attachments/assets/1a2a7391-2274-4be8-b000-dcf2db46a78d"> | 
| <img width="490" alt="image" src="https://github.com/user-attachments/assets/f8fb54cb-44f1-458c-80bc-14539773ce47"> | <img width="421" alt="image" src="https://github.com/user-attachments/assets/984f9fde-a8d1-448e-a09c-4e292cf5d014"> | 

Might be worth discussing the weight of this issue with the team and deciding a path forward

CC: @mejiaj  @amyleadem

2024-08-30 19:42 UTC, mahoneycm commented on css/uswds-next.scss
>    .next-section__subhead {
To clarify: I see it being used on the linked landing page, but nowhere else. I see the default background color and not the updated color tokens.

2024-09-05 22:40 UTC, amyleadem commented on _next/04-00-looking-ahead.md
This error is marked as "minor" in the scan. Since this is stemming from built-in Kramdown functionality, I lean towards leaving this  as-is for now and opening an issue to follow-up later. 

Alternatively, we could manually build out the citations and backlinks, but I fear that the benefit is not worth the effort at this time. 

Curious if you all have any objections.

2024-09-05 22:54 UTC, amyleadem commented on css/uswds-next.scss
>    .next-section__subhead {
I might understand your question, but I see the color update on the "Purpose" subhead on the [Next landing page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/rc-publish-header-checklist/next/).

2024-09-05 23:17 UTC, amyleadem requested changes
Thanks for your work on this @RachelCorsino and team! This is close - I just vote that we revert all of the footnote markup changes (more details in [this comment](https://github.com/uswds/uswds-site/pull/2783#discussion_r1746262752) and in the "details" section below). 

## Details

I curiously am not able to find any of the beta scans on cloud pages anymore. I am wondering if they removed them. For review, I relied on a locally downloaded version of the scan instead. 

In doing this, I discovered what appears to be false positives, so I think it is reasonable to treat the scan as a beta. My attitude is that any confirmed accessibility fix is a win here - we don't need to fix every flagged error. 

Here is a summary of the different errors that were flagged and their status after this PR:
1. Error: "Element has insufficient color contrast" (serious)
    1. I confirmed that the color contrast issues have all been addressed.
1. Error: "The role used is deprecated: doc-endnote" (minor)
    1. I recommend we open a new issue to investigate and update the `doc-endnote` items. This role is built into Kramdown and is marked in the scan as a minor error. Feels reasonable to investigate in a follow-up issue. If we are comfortable with this, can you revert the related updates in this PR @RachelCorsino?
1. Error: "ARIA attribute is not allowed: aria-multiselectable="true"" (Critical)
    1. I confirmed that this has been removed in all instances
1. Error: "Document does not have a non-empty <title> element" (Serious)
    1. This appears to be a false report. It is flagged on pages like the [checkbox page](https://designsystem.digital.gov/components/checkbox/) and [design principles](https://designsystem.digital.gov/design-principles/) (among others), but I see a `<title>` in the source code and axe devTools doesn't flag any errors. 
1. Error: "All touch targets must be 24px large, or leave sufficient space." (Serious)
    1. We have opened issue #2796 to address as a follow on.

2024-09-06 00:42 UTC, RachelCorsino commented on css/uswds-next.scss
> +  color: color("gray-60");
Resolved in [746633f](https://github.com/uswds/uswds-site/pull/2783/commits/746633ff5ba6990aa3b0015da629d8c63779e773). Good catch!

2024-09-06 00:55 UTC, RachelCorsino commented on _next/04-00-looking-ahead.md
Reverted back to original code

2024-09-06 00:55 UTC, RachelCorsino commented
@amycole501  - Related footnotes code has been reverted

2024-09-06 14:14 UTC, mahoneycm commented on css/uswds-next.scss
>    .next-section__subhead {
Ahh thank you @amyleadem ! Now I see the color changes in the "purpose", "findings", and "what's next" sections of this page!

Resolving this conversation

2024-09-06 22:28 UTC, amyleadem approved these changes
Thanks @RachelCorsino! Looks good to me.

2024-09-20 19:45 UTC, merged