USWDS-Site: Add changelog for in-page navigation [#6205]
uswds/uswds-site pull request #3000
Opened 2024-12-06 01:57 UTC by mlloydbixal

# Summary

Add a changelog for PR uswds/uswds#6205

>[!important]
> We need to update the changelog dates before merge.

## Preview link

[In-page navigation changelog](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/ml-changelog-6205/components/in-page-navigation/#changelog)

2024-12-10 18:06 UTC, mahoneycm commented
**Todo:** Update guidance to include this new data attribute

2025-01-03 20:39 UTC, amyleadem requested changes
Thanks for this, @mlloydbixal! I added a comment below with some suggestions for copy updates. 

Can you also add documentation for this new setting on the [settings page](https://designsystem.digital.gov/documentation/settings/#in-page-navigation) and in the [settings table on the in-page navigation page](https://designsystem.digital.gov/components/in-page-navigation/#component-settings-in-page-navigation)? 

Let me know if you have any questions.

2025-01-22 23:00 UTC, amyleadem commented on _data/changelogs/component-in-page-navigation.yml
> +    summaryAdditional: By default, this setting hides the in-page navigation component when there are fewer than two headings in the content region. Teams should customize the value of this setting b
```suggestion
  - date: NNNN-NN-NN
    summary: Added the `data-minimum-heading-count` property, which hides the component when the content region does not contain the designated minimum number of headings.
    summaryAdditional: By default, this property hides the in-page navigation component when there are fewer than two headings in the content region. Teams should customize the value of this property based on their content needs. 
```

2025-01-22 23:04 UTC, amyleadem commented on _components/in-page-navigation/in-page-navigation.md
> +      description: The minimum number of headings that determines when the in-page navigation should be displayed or hidden.
```suggestion
      description: The minimum number of headings needed in the content region to build the component on the page. 
```

2025-01-22 23:21 UTC, amyleadem commented on _data/changelogs/component-in-page-navigation.yml
> +    affectsSettings: true
**issue:** This affects the component properties, not settings. 
```suggestion
```

2025-01-22 23:23 UTC, amyleadem commented on _data/changelogs/component-in-page-navigation.yml
> +    affectsJavascript: true
```suggestion
    affectsStyles: true
```

2025-01-22 23:23 UTC, merged