USWDS-Site: Collection Accessibility Checklist
uswds/uswds-site pull request #3010
Opened 2024-12-10 19:50 UTC by cathybaptista

# Summary

Added accessibility test page for collection component

> [!Important]
> We need to update changelog dates before merge

## Related issue

Closes #2910 

## Preview link
[Collection Component Page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cb-publish-collection-checklist/components/collection/)
[Process List Accessibility Tests Page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cb-publish-collection-checklist/components/collection/accessibility-tests/)

## Testing and review
Follow these steps:

1. Confirm that both the main component page and the accessibility tests page have the correct compliance tag at the top.
2. Confirm that the main component page links to the accessibility tests page in the side navigation.
3. Confirm that the main component page links to the accessibility tests page from the accessibility guidance section.
4. Confirm that the main component page shows the accessibility tests summary.
5. Check that accessibility tests page provides the correct counts for each test status type.
6. Confirm the test checklist summaries and data are accurate.
7. Confirm no visual issues.
8. Confirm there is an appropriate changelog entry on both the main component page and the accessibility tests page.

## Manual Tests Run prior to submitting this PR:

- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `main`).
- [x] Run `npm run prettier:scss` to format any Sass updates.
- [x] Run `npm test` and confirm that all tests pass.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Confirm that both the main component page and the accessibility tests page have the correct compliance tag at the top.
- [x] Confirm that the main component page links to the accessibility tests page in the side navigation.
- [x] Confirm that the main component page links to the accessibility tests page from the accessibility guidance section.
- [x] Confirm that the main component page shows the accessibility tests summary.
- [x] Check that accessibility tests page provides the correct counts for each test status type.
- [x] Confirm the test checklist summaries and data are accurate.
- [x] Confirm no visual issues.
- [x] Confirm there is an appropriate changelog entry on both the main component page and the accessibility tests page.

2024-12-11 01:18 UTC, RachelCorsino reviewed
Just some tiny fixes that I noticed(:

2024-12-12 16:55 UTC, RachelCorsino submitted a review, later dismissed
Looks good to me! Approved!

2024-12-12 19:33 UTC, mahoneycm requested changes
Looks good @cathybaptista ! Two updates from what is listed on the checklist. Discussed on teams.

2024-12-12 19:33 UTC, mahoneycm commented on _data/accessibility-tests/collection.yml
> +    wcag_criterion: 1.1.1
**Suggestion:** Update the description to match [icon's 1.1.1 summary](https://arc.net/l/quote/riqvddqr)

> "**Icons provide a text alternative for screen readers when needed.** When you use a screen reader and navigate to a non-decorative icon, you hear an appropriate description of the icon. If the icon is purely decorative, you should not hear a description."

```suggestion
  - summary: Icons or graphics provide a text alternative for screen readers when needed.    
    summary_additional: When you use a screen reader and navigate to a non-decorative icon or graphic, you hear an appropriate description of the icon. If the icon is purely decorative, you should not hear a description.
    test_status: conditional
    test_type: screen_reader
    version_tested: 3.8.2
    wcag_criterion: 1.1.1
```

2024-12-12 19:33 UTC, mahoneycm commented on _data/accessibility-tests/collection.yml
> +    wcag_criterion: 2.4.4
**Todo:** We decided to update this test to `conditional` since users are responsible for adding the links.

2024-12-12 19:35 UTC, mahoneycm commented
Also, can you resolve any comments that are finished to clean up the thread a bit? It'll give us a better snapshot of where this PR is at!

2024-12-12 22:34 UTC, amyleadem requested changes
Looking good! Just requested some very minor tweaks in the comments below.

2024-12-12 22:34 UTC, amyleadem commented on _data/changelogs/component-collection-accessibility.yml
> +    githubRepo: uswds-site
**polish:** Add extra line at end of file for code formatting
```suggestion
    githubRepo: uswds-site
    
```

2024-12-13 20:33 UTC, amyleadem approved these changes
LGTM! Thanks @cathybaptista

2024-12-13 20:48 UTC, mlloydbixal submitted a review, later dismissed
All looks good :) thanks

2024-12-18 16:19 UTC, mahoneycm submitted a review, later dismissed
LGTM!

2024-12-18 21:34 UTC, annepetersen approved these changes
LGTM

2024-12-18 22:06 UTC, merged