Add November summary to Monthly calls page
uswds/uswds-site pull request #3015
Opened 2024-12-12 20:25 UTC by finekatie

# Summary

Adding November Monthly Call content to Monthly Calls page 

> [!Important]
> The changelog date will need to be updated before merge.

## Related issue

Closes #6215

## Preview link 
[Monthly calls page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-novMC-MCspage/about/monthly-calls/)

## Problem statement

Needed to get Monthly calls page up to date with November call info. 

## Solution
November Monthly call summary was approved and is ready to be added to the page. Video will not be going up until later in the month. Will need a new ticket or branch off this when it's ready.

## Testing and review

Need someone to look and make sure links work and content is clean and clear.

2024-12-12 22:44 UTC, annepetersen requested changes

2024-12-12 22:44 UTC, annepetersen commented on _data/monthly-calls.yml
believe you'll need to use Markup, not HTML, for the link to the design kit. Also there's a random "date: October 2024" that seems be hanging out at the end of the paragraph

2024-12-12 22:47 UTC, finekatie commented on _data/monthly-calls.yml
Ah! Thank you for the link info - will look and see about that and the October date issue.

2024-12-13 00:21 UTC, annepetersen requested changes
I think the number of slides for November is 108, not 109?

2024-12-13 14:37 UTC, finekatie commented
> I think the number of slides for November is 108, not 109?

DG has 109 on their event page. That's where I normally pull from. I see the slide deck is 108. I will change to 108 and alert DG if you like.

2024-12-13 15:33 UTC, annepetersen approved these changes
LGTM, thanks

2024-12-13 15:33 UTC, merged